In [1]:
import numpy as np

In [3]:
gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])
gdp_array

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [7]:
gdp_array[1]

array([39169, 34406, 32821, 35387, 38299, 37813])

In [9]:
gdp_array[1][3]

35387

In [11]:
gdp_array[1, 3]

35387

In [13]:
gdp_array[1:3, 2:5]

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [15]:
gdp_array[:3, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [17]:
gdp_array[:, 2:5]

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])